name: aaaaSignin
 
on:
  schedule:
   # 每天国际时间 17:20 运行一次, 中国时间 01:20
    - cron: '01 00 * * *'
    - cron: '30 00 * * *'
    - cron: '01 01 * * *'
  workflow_dispatch:
  
jobs:
  signin:
    name: aaaaSignin
    runs-on: ubuntu-latest
    steps:
      - uses: FloodLin/test@main
        with:
          GP_TOKEN: ${{ secrets.GP_TOKEN}}
          PUSHPLUS_TOKEN: ${{ secrets.PUSHPLUS_TOKEN }}
          Mobile_No: ${{ secrets.Mobile }}
          province_Name: ${{ secrets.province }}
          city_Name: ${{ secrets.city }}
          ID_TOKEN: ${{ secrets.ID_TOKEN }}
          user_Id: ${{ secrets.userId }}
          lat: ${{ secrets.lat }}
          lng: ${{ secrets.lng }}
 
